[project]
name = "multilingual-ner-and-sentiment-analysis-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "pydantic>=2.13.4",
]

[project.optional-dependencies]
api = [
    "accelerate>=1.14.0",
    "datasets>=5.0.0",
    "evaluate>=0.4.6",
    "fastapi>=0.136.3",
    "langdetect>=1.0.9",
    "seqeval>=1.2.2",
    "torch>=2.5.1",
#    "torchvision>=0.20.1",
    "transformers>=5.12.0",
    "uvicorn>=0.49.0",
]
ui = [
    "gradio>=6.18.0",
    "requests>=2.34.2",
]
train = [
    "wandb>=0.27.2",
]
# api = [
#     "accelerate>=1.13.0",
#     "datasets>=5.0.0",
#     "evaluate>=0.4.6",
#     "fastapi>=0.136.3",
#     "langdetect>=1.0.9",
#     "seqeval>=1.2.2",
#     "torch>=2.5.1+cu121",
#     "transformers>=5.12.0",
#     "uvicorn>=0.49.0",
# ]
# ui = [
#     "gradio>=6.18.0",
#     "requests>=2.32.0",
# ]
# train = [
#     "wandb>=0.27.2",
# ]

[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-gpu" }


[tool.setuptools.packages.find]
where = ["."]
include = ["configs*", "models*", "NLP*"]
namespaces = false

# [project]
# name = "multilingual-ner-and-sentiment-analysis-system"
# version = "0.1.0"
# description = "Add your description here"
# readme = "README.md"
# requires-python = "==3.12.*"
# dependencies = [
#     "accelerate>=1.13.0",
#     "datasets>=5.0.0",
#     "evaluate>=0.4.6",
#     "fastapi>=0.136.3",
#     "gradio>=6.16.0",
#     "langdetect>=1.0.9",
#     "pydantic>=2.13.4",
#     "seqeval>=1.2.2",
#     "torch>=2.5.1",
#     "transformers>=5.10.2",
#     "uvicorn>=0.49.0",
#     "wandb>=0.27.2",
# ]
# 
# [[tool.uv.index]]
# name = "pytorch-gpu"
# url = "https://download.pytorch.org/whl/cu121"
# explicit = true
# 
# [tool.uv.sources]
# torch = { index = "pytorch-gpu" }
# torchvision = { index = "pytorch-gpu" }
# torchaudio = { index = "pytorch-gpu" }
# [tool.setuptools.packages.find]
# where = ["."]
# include = ["configs*", "models*", "NLP*"]
# namespaces = false